### ISSUE TITLE
Null-terminated string encoding problem

### ISSUE THREAD

**Issue by zastruga** [Tyulis/rawutil#4]
During the refactor in v2.6 the encoding of null-terminated strings was updated to append the null-terminator with a bytes datatype.  This results in `str + bytes`, raising an exception.  One possible fix is to encode the input string as a `bytes` object as well.  At the moment, I've reverted to v2.5 to avoid the issue.

`rawutil.pack('n', 'testing')` fails, but prior to v2.6 this worked fine.
`rawutil.pack('n', b'testing')` works in v2.6.

https://github.com/Tyulis/rawutil/blob/1e29e2f0197b3903f216db4de6eef8da00fd2200/rawutil.py#L624

**Comment by Tyulis** [comment]
Indeed, it’s now fixed for both `n` and `s` formats, thanks for pointing this out !
It’s updated here and on PyPI.
